# Generated by Django 3.2.4 on 2024-06-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_created=True)),
                ('uname', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_created=True)),
                ('publisher', models.CharField(max_length=255)),
                ('date_e', models.DateTimeField(auto_now_add=True)),
                ('c_view', models.IntegerField(default=0)),
                ('disc', models.TextField()),
            ],
        ),
    ]
