# Generated by Django 3.2.4 on 2024-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0003_auto_20240626_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.CharField(max_length=470),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Null', max_length=80),
        ),
    ]
