# Generated by Django 3.2.4 on 2024-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0007_alter_post_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='c_view',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
