# Generated by Django 3.2.4 on 2024-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0009_auto_20240626_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
