# Generated by Django 3.2.4 on 2024-06-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0010_alter_post_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixe.post'),
        ),
    ]
