# Generated by Django 3.2.4 on 2024-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0013_rename_date_modified_post_p_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/1571774856481.jpg', upload_to='blog/'),
        ),
    ]
