# Generated by Django 3.2.4 on 2024-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0014_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/1571774856481.jpg', upload_to='blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='pixe.Categoris'),
        ),
    ]
