# Generated by Django 3.2.4 on 2024-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0015_auto_20240629_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
                ('birthday', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
