# Generated by Django 3.2.4 on 2024-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0016_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='uname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(),
        ),
    ]
