# Generated by Django 3.2.4 on 2024-07-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixe', '0017_auto_20240702_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='female',
        ),
        migrations.RemoveField(
            model_name='users',
            name='male',
        ),
        migrations.AddField(
            model_name='users',
            name='subject',
            field=models.TextField(default=None, null=True),
        ),
    ]
